import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    appName: 'LimbahGuna',
    tagline: 'Energi Hijau untuk Masa Depan',

    navHome: 'Beranda',
    navActivity: 'Beranda',
    navMarketplace: 'Pasar',
    navSupply: 'Setor',
    navCalculator: 'Kalkulator',
    navProfile: 'Profil',
    navScan: 'Scan',
    navRobot: 'Robot',

    // AI Scan translations
    scanTitle: 'Pusat Analisis Biomassa',
    scanSubtitle: 'Analisis kualitas biomassa dengan teknologi AI',
    scanDesc: 'Analisis kualitas biomass menggunakan AI grading',
    demoMode: 'Mode Demo',
    selectDemoMode: 'Pilih mode demo grading:',
    scanning: 'Menganalisis biomass...',
    scanComplete: 'Scan Selesai!',
    cameraPlaceholder: 'Preview kamera akan muncul di sini',
    demoReady: 'Mode demo siap - tap Scan untuk simulasi',
    enableDemo: 'Aktifkan mode demo untuk menguji',
    scanningBtn: 'Memindai...',
    scanBtn: 'Scan Biomass',
    newScan: 'Scan Baru',
    gradeResult: 'Hasil Grading',
    moisture: 'Kadar Air',
    calorificValue: 'Nilai Kalori',
    recommendation: 'Rekomendasi',
    aiConfidence: 'Kepercayaan AI',
    aboutAIScan: 'Tentang AI Scan',
    aiScanInfo: 'Fitur ini menggunakan computer vision untuk menganalisis sampel biomass dan menentukan grade kualitas, kadar air, dan potensi energi. Aktifkan mode demo untuk simulasi proses scanning.',
    uploadBtn: 'Upload Gambar',
    uploadPrompt: 'Pilih atau letakkan foto di sini',
    uploadHint: 'Mendukung format JPG, PNG, WEBP',
    changeImage: 'Ganti',
    analyzeBtn: 'Analisis',
    analyzing: 'Menjalankan pipeline analisis...',
    perceptionResult: 'Hasil Analisis',
    biomassType: 'Jenis Biomassa',
    contaminationAlert: 'Peringatan Kontaminasi',
    aiScanBtn: 'Mulai AI Scan Biomassa',
    carbonSavedLabel: 'Diselamatkan',
    carbonSyncSuccess: 'Sukses! Anda baru saja menyelamatkan {amount} kg emisi CO₂',
    carbonSyncSuccessTitle: 'Smart Carbon Sync',

    // Robot Command Center translations
    robotTitle: 'Robot Command Center',
    robotDesc: 'Sistem Kontrol Robotika Agentik',
    vultrVM: 'Vultr VM - Central Brain',
    vmConnected: 'Terhubung • Latensi rendah',
    vmConnecting: 'Menghubungkan...',
    '3dSimulation': 'Area Simulasi 3D',
    '3dPlaceholder': 'Visualisasi robot real-time',
    startSimulation: 'Mulai Simulasi',
    stopSimulation: 'Hentikan Simulasi',
    liveMode: 'Mode Live',
    activeAgents: 'Robot Agent Aktif',
    taskLogs: 'Log Tugas Real-time',
    vultrPowered: 'Diperkuat oleh Vultr VM',
    vultrInfo: 'Central brain untuk sistem robotika agentik kami berjalan di infrastruktur Vultr Cloud, memungkinkan koordinasi real-time dan pengambilan keputusan berbasis AI untuk penyortiran dan pemrosesan biomass.',

    heroTitle: 'Limbahku Energiku',
    heroSubtitle: 'Aksi Kecil, Manfaat Maksimal',
    totalWaste: 'Total Sampah',
    carbonSaved: 'Carbon Diselamatkan',
    collected: 'kg terkumpul',
    productCategories: 'Kategori Produk',
    didYouKnowTitle: 'Tahukah Anda?',
    didYouKnowText: 'Setiap 1 ton biomass yang digunakan dapat mengurangi emisi CO₂ hingga 1.5 ton dibandingkan batu bara!',

    yourImpact: 'Dampak Anda',
    wasteCollected: 'kg Sampah Terkumpul',
    yourPoints: 'Poin Anda',
    continueCollecting: 'Terus kumpulkan poin dengan menyetor limbah!',

    popularCategories: 'Kategori Populer',
    woodPellet: 'Wood Pellet',
    palmShell: 'Cangkang Sawit',
    sawdust: 'Serbuk Kayu',
    woodChip: 'Wood Chip',

    whyBioEnergy: 'Mengapa LimbahGuna?',
    ecoFriendlyTitle: '🌍 Ramah Lingkungan',
    ecoFriendlyDesc: 'Kurangi emisi karbon dengan menggunakan biomass sebagai alternatif energi',
    economicalTitle: '💰 Ekonomis',
    economicalDesc: 'Dapatkan penghasilan tambahan dari limbah organik Anda',
    trustedTitle: '🤝 Terpercaya',
    trustedDesc: 'Platform yang menghubungkan supplier, produsen, dan pembeli secara aman',

    marketplaceTitle: 'Pasar',
    marketplaceDesc: 'Jual beli biomass berkualitas',
    filterCategory: 'Filter Kategori',
    selectCategory: 'Pilih Kategori:',
    allProducts: 'Semua Produk',
    showing: 'Menampilkan',
    products: 'produk',
    perTon: 'per ton',
    stockAvailable: 'Stok tersedia',
    contactSeller: 'Hubungi Penjual',
    contacting: 'Menghubungi',
    chatComingSoon: 'Fitur chat akan segera tersedia!',
    noProducts: 'Tidak ada produk dalam kategori ini',

    supplyTitle: 'Setor Limbah',
    supplySubtitle: 'Ubah limbah biomass Anda menjadi poin reward',
    supplyDesc: 'Ubah limbah Anda menjadi nilai tambah',
    rewardBanner: 'Dapatkan Reward!',
    rewardBannerDesc: 'Setiap penyetoran mendapat 100 poin yang bisa ditukar dengan produk energi',
    totalPoints: 'Total Poin Anda',
    pointsInfo: 'Setiap 10 kg limbah = 1 poin. Kumpulkan lebih banyak poin!',
    offerSent: 'Penawaran Berhasil Dikirim!',
    producerWillContact: 'Produsen akan segera menghubungi Anda untuk penjemputan',
    wasteType: 'Jenis Limbah',
    selectWasteType: 'Pilih jenis limbah',
    estimatedWeight: 'Estimasi Berat (kg)',
    weightPlaceholder: 'Contoh: 50',
    wastePhoto: 'Foto Limbah',
    clickToUpload: 'Klik untuk upload foto limbah',
    optional: '(Opsional)',
    pickupAddress: 'Alamat Penjemputan',
    addressPlaceholder: 'Masukkan alamat lengkap untuk penjemputan limbah',
    sendOffer: 'Kirim Penawaran ke Produsen',
    sending: 'Mengirim...',
    selectWaste: 'Pilih jenis limbah',
    enterValidWeight: 'Masukkan berat yang valid',
    enterAddress: 'Alamat penjemputan wajib diisi',
    errorOccurred: 'Terjadi Kesalahan',
    howItWorks: 'Cara Kerja',
    step1: 'Isi form detail limbah yang akan disetor',
    step2: 'Produsen akan mereview dan approve penawaran Anda',
    step3: 'Tim penjemputan akan datang ke alamat Anda',
    step4: 'Dapatkan poin reward yang bisa ditukar dengan produk energi',
    detailWaste: 'Detail Limbah',

    wood: 'Kayu',
    palmKernelShell: 'Cangkang Sawit',
    bamboo: 'Bambu',
    straw: 'Jerami',
    cornCob: 'Tongkol Jagung',
    riceHusk: 'Sekam Padi',
    other: 'Lainnya',

    calculatorTitle: 'Kalkulator Carbon Credit',
    calculatorDesc: 'Hitung dampak lingkungan Anda',
    selectBiomass: 'Pilih Bahan Bakar Biomass',
    selectType: '-- Pilih Jenis --',
    usageAmount: 'Jumlah Penggunaan (Ton)',
    amountPlaceholder: 'Contoh: 10',
    calculate: 'Hitung',
    reset: 'Reset',
    selectFuel: 'Pilih jenis bahan bakar pengganti',
    enterValidAmount: 'Masukkan jumlah yang valid',
    carbonPotential: 'Potensi Kredit Karbon',
    environmentalImpact: 'Dampak Lingkungan',
    equivalentTo: 'Setara dengan',
    treesSaved: 'Pohon yang diselamatkan',
    comparedToCoal: 'Jika dibandingkan dengan batu bara',
    emissionReduction: 'Pengurangan emisi hingga',
    contributionTo: 'Kontribusi untuk',
    netZeroTarget: 'Mencapai target Net Zero Emission 2050',
    interestingFacts: 'Fakta Menarik',
    fact1: 'Biomass adalah sumber energi terbarukan yang mengurangi ketergantungan pada bahan bakar fosil',
    fact2: 'Menggunakan biomass membantu mengurangi limbah yang berakhir di TPA',
    fact3: 'Setiap ton biomass yang digunakan berkontribusi pada pengurangan emisi gas rumah kaca global',
    conversionFactors: 'Faktor Konversi',
    factorNote: '* Angka ini adalah estimasi berdasarkan perbandingan dengan penggunaan batu bara',

    organicWaste: 'Sampah Organik',

    profileTitle: 'Profil',
    memberSince: 'Member sejak',
    contactInfo: 'Informasi Kontak',
    achievements: 'Pencapaian',
    totalDeposits: 'Total Setor',
    pointsCollected: 'Poin Terkumpul',
    times: 'kali',
    depositHistory: 'Riwayat Penyetoran',
    noHistory: 'Belum ada riwayat penyetoran',
    approved: 'Disetujui',
    pending: 'Menunggu',
    settings: 'Pengaturan',
    logout: 'Keluar',
    contactUs: 'Hubungi Kami',
    contactDesc: 'Bantuan & Layanan Pelanggan',
    thankYou: 'Terima kasih',
    contributionMessage: 'telah berkontribusi untuk lingkungan yang lebih baik!',

    january: 'Januari',
    february: 'Februari',
    march: 'Maret',
    april: 'April',
    may: 'Mei',
    june: 'Juni',
    july: 'Juli',
    august: 'Agustus',
    september: 'September',
    october: 'Oktober',
    november: 'November',
    december: 'Desember',

    home: {
      producerRequestTitle: 'Permintaan Penjemputan Limbah',
      noRequest: 'Tidak ada permintaan baru',
      requestWillAppear: 'Request setor akan muncul di sini',
      wasteType: 'Jenis Limbah',
      weight: 'Berat',
      location: 'Lokasi',
      wastePhoto: 'Foto Limbah',
      acceptButton: 'Terima & Jemput',
      processing: 'Memproses...',
      contactSupplier: 'Hubungi Penyetor',
      photoNotAvailable: 'Foto tidak tersedia',
      confirmPickup: 'Apakah Anda yakin ingin menerima dan menjemput limbah ini?',
      requestAccepted: 'Permintaan diterima! Segera hubungi penyetor untuk penjemputan.',
      requestFailed: 'Gagal menerima permintaan. Silakan coba lagi.',
      historyTitle: 'Riwayat Penyetoran',
      noHistory: 'Belum ada riwayat penyetoran'
    },

    profile: {
      title: 'Profil Saya',
      memberSince: 'Member sejak',
      contactInfo: 'Informasi Kontak',
      accountType: 'Jenis Akun',
      roleProducer: 'Mitra Produsen',
      rolePublic: 'Sobat Limbah',
      phone: 'Nomor Telepon',
      address: 'Alamat',
      emptyPhone: 'Belum diisi',
      emptyAddress: 'Belum diisi',
      editProfile: 'Edit Profil',
      securityTitle: 'Keamanan Akun',
      changePassword: 'Ubah Password',
      oldPassword: 'Password Lama',
      newPassword: 'Password Baru',
      confirmPassword: 'Konfirmasi Password Baru',
      savePassword: 'Simpan Password Baru',
      passwordSuccess: 'Password berhasil diubah!',
      passwordError: 'Gagal mengubah password',
      oldPasswordWrong: 'Password lama salah!',
      allFieldsRequired: 'Semua field harus diisi',
      passwordMinLength: 'Password baru minimal 6 karakter',
      passwordNotMatch: 'Password baru tidak cocok',
      contactUs: 'Hubungi Kami',
      logout: 'Keluar',
      logoutConfirm: 'Apakah Anda yakin ingin keluar?',
      processing: 'Memproses...',
      saving: 'Menyimpan...',
      fullName: 'Nama Lengkap',
      phoneNumber: 'Nomor Telepon / WhatsApp',
      fullAddress: 'Alamat Lengkap',
      saveChanges: 'Simpan Perubahan',
      cancel: 'Batal',
      notFilled: 'Belum diisi',
      profileUpdated: 'Profil berhasil diperbarui!',
      profileUpdateFailed: 'Gagal memperbarui profil',
      nameRequired: 'Nama lengkap tidak boleh kosong',
      enterFullName: 'Masukkan nama lengkap',
      phoneExample: 'Contoh: 08123456789',
      enterFullAddress: 'Masukkan alamat lengkap'
    },

    wasteTypes: {
      wood_pellet: 'Wood Pellet',
      wood_chip: 'Wood Chip',
      sawdust: 'Serbuk Kayu',
      sampah_rumah: 'Sampah Rumah Tangga',
      potongan_kayu: 'Potongan Kayu',
      cangkang_sawit: 'Cangkang Sawit',
      'Wood Pellet': 'Wood Pellet',
      'Wood Chip': 'Wood Chip',
      'Cangkang Sawit': 'Cangkang Sawit',
      'Serbuk Kayu': 'Serbuk Kayu'
    },

    productForm: {
      title: 'Tambah Produk Biomass',
      labelName: 'Nama Produk',
      labelCategory: 'Kategori',
      labelPrice: 'Harga per Kg (Rp)',
      labelStock: 'Stok Tersedia (Ton)',
      labelLocation: 'Lokasi',
      labelWhatsApp: 'Nomor WhatsApp (Wajib)',
      helperWhatsApp: 'Pembeli akan menghubungi Anda melalui nomor ini',
      labelPhoto: 'Upload Foto Produk (Wajib)',
      labelDesc: 'Deskripsi Produk',
      placeholderName: 'contoh: Wood Pellet Grade A',
      placeholderPrice: 'contoh: 1500',
      placeholderStock: 'contoh: 100',
      placeholderLocation: 'contoh: Jakarta',
      placeholderWhatsApp: '08123456789',
      placeholderDesc: 'Deskripsi singkat tentang produk Anda (opsional)',
      btnCancel: 'Batal',
      btnSave: 'Simpan Produk',
      btnUploading: 'Mengupload...',
      errorName: 'Nama produk wajib diisi',
      errorPrice: 'Harga harus lebih dari 0',
      errorStock: 'Stok harus lebih dari 0',
      errorWhatsApp: 'Nomor WhatsApp wajib diisi',
      errorPhoto: 'Foto produk wajib diupload',
      successAdd: 'Produk berhasil ditambahkan!',
      successUpdate: 'Produk berhasil diperbarui!',
      errorAdd: 'Gagal menambahkan produk',
      stockUnit: 'ton',
      available: 'tersedia'
    },

    landing: {
      heroTitle: 'LimbahGuna',
      heroSubtitle: 'Platform Digital untuk Pengelolaan Limbah dan Energi Berkelanjutan',
      featuresTitle: 'Fitur Unggulan',
      feature1Title: 'Setor Limbah Biomassa',
      feature1Desc: 'Jual limbah wood pellet, cangkang sawit, dll.',
      feature2Title: 'Marketplace Biomassa',
      feature2Desc: 'Beli bahan bakar biomassa berkualitas.',
      feature3Title: 'Kalkulator Carbon',
      feature3Desc: 'Hitung dampak pengurangan emisi CO2.',
      feature4Title: 'Sistem Poin Reward',
      feature4Desc: 'Dapatkan poin dari setiap penyetoran.',
      stats1Label: 'Kg Biomassa Terkumpul',
      stats2Label: 'Kg CO2 Terselamatkan',
      btnCta: 'Masuk / Daftar Sekarang',
      footerText: '© 2025 LimbahGuna. Platform Ekonomi Sirkular Indonesia.',
      footerBy: 'By PT Energi Jaya Integra.',
      howItWorksTitle: 'Cara Kerja',
      step1Title: 'Foto Sampah Anda',
      step1Desc: 'Arahkan kamera ke sampah atau limbah di sekitar Anda. Sistem AI kami akan mengenali jenis dan kualitasnya secara otomatis.',
      step2Title: 'Proses Cepat',
      step2Desc: 'Foto Anda diproses sekejap oleh pusat kendali kami untuk memberikan instruksi langsung ke sistem pemilah.',
      step3Title: 'Dapatkan Hadiah',
      step3Desc: 'Limbah dipilah ke tempat yang benar, dan Anda otomatis mendapatkan poin reward yang bisa ditukar dengan berbagai hadiah menarik.'
    },

    auth: {
      back: 'Kembali',
      roleTitle: 'Pilih Peran Anda',
      roleSubtitle: 'Bergabung dengan ekosistem ekonomi sirkular LimbahGuna',
      producerTitle: 'Mitra Produsen',
      producerDesc: 'Saya mengolah limbah & menjual produk biomass',
      producerFeature1: 'Kelola produk di Marketplace',
      producerFeature2: 'Validasi setoran limbah dari masyarakat',
      producerFeature3: 'Dashboard produsen lengkap',
      publicTitle: 'Sobat Lingkungan',
      publicDesc: 'Saya menyetor limbah & membeli produk energi',
      publicFeature1: 'Setor limbah biomass & dapatkan poin',
      publicFeature2: 'Belanja produk energi di Marketplace',
      publicFeature3: 'Akses kalkulator karbon',
      welcomeTitle: 'Selamat Datang',
      welcomeSubtitle: 'Masuk ke akun LimbahGuna Anda',
      registerTitle: 'Lengkapi data untuk mendaftar',
      labelName: 'Nama Lengkap',
      labelEmail: 'Email',
      labelPassword: 'Password',
      placeholderName: 'Masukkan nama lengkap',
      placeholderEmail: 'email@contoh.com',
      placeholderPassword: 'Minimal 6 karakter',
      btnLogin: 'Masuk',
      btnRegister: 'Daftar Sekarang',
      btnProcessing: 'Memproses...',
      haveAccount: 'Sudah punya akun?',
      noAccount: 'Belum punya akun?',
      linkLogin: 'Masuk',
      linkRegister: 'Daftar',
      regSuccess: 'Registrasi berhasil! Silakan cek email Anda untuk konfirmasi akun.'
    }
  },
  en: {
    appName: 'LimbahGuna',
    tagline: 'Green Energy for the Future',

    navHome: 'Home',
    navActivity: 'Home',
    navMarketplace: 'Market',
    navSupply: 'Supply',
    navCalculator: 'Calculator',
    navProfile: 'Profile',
    navScan: 'Scan',
    navRobot: 'Robot',

    // AI Scan translations
    scanTitle: 'Biomass Analysis Center',
    scanSubtitle: 'Analyze biomass quality with AI technology',
    scanDesc: 'Analyze biomass quality using AI-powered grading',
    demoMode: 'Demo Mode',
    selectDemoMode: 'Select demo grading mode:',
    scanning: 'Analyzing biomass...',
    scanComplete: 'Scan Complete!',
    cameraPlaceholder: 'Camera preview will appear here',
    demoReady: 'Demo mode ready - tap Scan to simulate',
    enableDemo: 'Enable demo mode to test',
    scanningBtn: 'Scanning...',
    scanBtn: 'Scan Biomass',
    newScan: 'New Scan',
    gradeResult: 'Grading Result',
    moisture: 'Moisture Content',
    calorificValue: 'Calorific Value',
    recommendation: 'Recommendation',
    aiConfidence: 'AI Confidence',
    aboutAIScan: 'About AI Scan',
    aiScanInfo: 'This feature uses computer vision to analyze biomass samples and determine their quality grade, moisture content, and energy potential. Enable demo mode to simulate the scanning process.',
    uploadBtn: 'Upload Picture',
    uploadPrompt: 'Select or drop a photo here',
    uploadHint: 'Supports JPG, PNG, WEBP formats',
    changeImage: 'Change',
    analyzeBtn: 'Analyze',
    analyzing: 'Running analysis pipeline...',
    perceptionResult: 'Analysis Result',
    biomassType: 'Biomass Type',
    contaminationAlert: 'Contamination Alert',
    aiScanBtn: 'Start AI Biomass Scan',
    carbonSavedLabel: 'Saved',
    carbonSyncSuccess: 'Success! You just saved {amount} kg of CO₂ emissions',
    carbonSyncSuccessTitle: 'Smart Carbon Sync',

    // Robot Command Center translations
    robotTitle: 'Robot Command Center',
    robotDesc: 'Agentic Robotics Control System',
    vultrVM: 'Vultr VM - Central Brain',
    vmConnected: 'Connected • Low latency',
    vmConnecting: 'Connecting...',
    '3dSimulation': '3D Simulation Area',
    '3dPlaceholder': 'Real-time robot visualization',
    startSimulation: 'Start Simulation',
    stopSimulation: 'Stop Simulation',
    liveMode: 'Live Mode',
    activeAgents: 'Active Robot Agents',
    taskLogs: 'Real-time Task Logs',
    vultrPowered: 'Powered by Vultr VM',
    vultrInfo: 'The central brain for our agentic robotics system runs on Vultr Cloud infrastructure, enabling real-time coordination and AI-powered decision making for biomass sorting and processing.',

    heroTitle: 'My Waste, My Energy',
    heroSubtitle: 'Small Action, Maximum Impact',
    totalWaste: 'Total Waste',
    carbonSaved: 'Carbon Saved',
    collected: 'kg collected',
    productCategories: 'Product Categories',
    didYouKnowTitle: 'Did You Know?',
    didYouKnowText: 'Every 1 ton of biomass used can reduce CO₂ emissions by up to 1.5 tons compared to coal!',

    yourImpact: 'Your Impact',
    wasteCollected: 'kg Waste Collected',
    yourPoints: 'Your Points',
    continueCollecting: 'Keep collecting points by supplying waste!',

    popularCategories: 'Popular Categories',
    woodPellet: 'Wood Pellet',
    palmShell: 'Palm Shell',
    sawdust: 'Sawdust',
    woodChip: 'Wood Chip',

    whyBioEnergy: 'Why LimbahGuna?',
    ecoFriendlyTitle: '🌍 Eco-Friendly',
    ecoFriendlyDesc: 'Reduce carbon emissions by using biomass as an alternative energy source',
    economicalTitle: '💰 Economical',
    economicalDesc: 'Earn extra income from your organic waste',
    trustedTitle: '🤝 Trusted',
    trustedDesc: 'A platform that connects suppliers, producers, and buyers securely',

    marketplaceTitle: 'Marketplace',
    marketplaceDesc: 'Buy and sell quality biomass',
    filterCategory: 'Filter Category',
    selectCategory: 'Select Category:',
    allProducts: 'All Products',
    showing: 'Showing',
    products: 'products',
    perTon: 'per ton',
    stockAvailable: 'Stock available',
    contactSeller: 'Contact Seller',
    contacting: 'Contacting',
    chatComingSoon: 'Chat feature coming soon!',
    noProducts: 'No products in this category',

    supplyTitle: 'Supply Waste',
    supplySubtitle: 'Turn your biomass waste into reward points',
    supplyDesc: 'Turn your waste into value',
    rewardBanner: 'Get Rewards!',
    rewardBannerDesc: 'Earn 100 points for every supply that can be exchanged for energy products',
    totalPoints: 'Your Total Points',
    pointsInfo: 'Every 10 kg of waste = 1 point. Collect more points!',
    offerSent: 'Offer Sent Successfully!',
    producerWillContact: 'A producer will contact you soon for pickup',
    wasteType: 'Waste Type',
    selectWasteType: 'Select waste type',
    estimatedWeight: 'Estimated Weight (kg)',
    weightPlaceholder: 'Example: 50',
    wastePhoto: 'Waste Photo',
    clickToUpload: 'Click to upload waste photo',
    optional: '(Optional)',
    pickupAddress: 'Pickup Address',
    addressPlaceholder: 'Enter complete address for waste pickup',
    sendOffer: 'Send Offer to Producer',
    sending: 'Sending...',
    selectWaste: 'Select waste type',
    enterValidWeight: 'Enter a valid weight',
    enterAddress: 'Pickup address is required',
    errorOccurred: 'Error Occurred',
    howItWorks: 'How It Works',
    step1: 'Fill out the waste details form',
    step2: 'Producer will review and approve your offer',
    step3: 'Pickup team will come to your address',
    step4: 'Get reward points that can be exchanged for energy products',
    detailWaste: 'Waste Details',

    wood: 'Wood',
    palmKernelShell: 'Palm Kernel Shell',
    bamboo: 'Bamboo',
    straw: 'Straw',
    cornCob: 'Corn Cob',
    riceHusk: 'Rice Husk',
    other: 'Other',

    calculatorTitle: 'Carbon Credit Calculator',
    calculatorDesc: 'Calculate your environmental impact',
    selectBiomass: 'Select Biomass Fuel',
    selectType: '-- Select Type --',
    usageAmount: 'Usage Amount (Tons)',
    amountPlaceholder: 'Example: 10',
    calculate: 'Calculate',
    reset: 'Reset',
    selectFuel: 'Select alternative fuel type',
    enterValidAmount: 'Enter a valid amount',
    carbonPotential: 'Carbon Credit Potential',
    environmentalImpact: 'Environmental Impact',
    equivalentTo: 'Equivalent to',
    treesSaved: 'Trees saved',
    comparedToCoal: 'Compared to coal',
    emissionReduction: 'Emission reduction up to',
    contributionTo: 'Contribution to',
    netZeroTarget: 'Achieving Net Zero Emission 2050 target',
    interestingFacts: 'Interesting Facts',
    fact1: 'Biomass is a renewable energy source that reduces dependence on fossil fuels',
    fact2: 'Using biomass helps reduce waste ending up in landfills',
    fact3: 'Each ton of biomass used contributes to reducing global greenhouse gas emissions',
    conversionFactors: 'Conversion Factors',
    factorNote: '* These figures are estimates based on comparison with coal usage',

    organicWaste: 'Organic Waste',

    profileTitle: 'Profile',
    memberSince: 'Member since',
    contactInfo: 'Contact Information',
    achievements: 'Achievements',
    totalDeposits: 'Total Deposits',
    pointsCollected: 'Points Collected',
    times: 'times',
    depositHistory: 'Deposit History',
    noHistory: 'No deposit history yet',
    approved: 'Approved',
    pending: 'Pending',
    settings: 'Settings',
    logout: 'Logout',
    contactUs: 'Contact Us',
    contactDesc: 'Help & Customer Support',
    thankYou: 'Thank you',
    contributionMessage: 'for contributing to a better environment!',

    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',

    home: {
      producerRequestTitle: 'Waste Pickup Requests',
      noRequest: 'No new requests',
      requestWillAppear: 'Supply requests will appear here',
      wasteType: 'Waste Type',
      weight: 'Weight',
      location: 'Location',
      wastePhoto: 'Waste Photo',
      acceptButton: 'Accept & Pickup',
      processing: 'Processing...',
      contactSupplier: 'Contact Supplier',
      photoNotAvailable: 'Photo not available',
      confirmPickup: 'Are you sure you want to accept and pick up this waste?',
      requestAccepted: 'Request accepted! Please contact the supplier for pickup.',
      requestFailed: 'Failed to accept request. Please try again.',
      historyTitle: 'Supply History',
      noHistory: 'No supply history yet'
    },

    profile: {
      title: 'My Profile',
      memberSince: 'Member since',
      contactInfo: 'Contact Information',
      accountType: 'Account Type',
      roleProducer: 'Producer Partner',
      rolePublic: 'Eco Partner',
      phone: 'Phone Number',
      address: 'Address',
      emptyPhone: 'Not filled',
      emptyAddress: 'Not filled',
      editProfile: 'Edit Profile',
      securityTitle: 'Account Security',
      changePassword: 'Change Password',
      oldPassword: 'Old Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm New Password',
      savePassword: 'Save New Password',
      passwordSuccess: 'Password changed successfully!',
      passwordError: 'Failed to change password',
      oldPasswordWrong: 'Old password is incorrect!',
      allFieldsRequired: 'All fields are required',
      passwordMinLength: 'New password must be at least 6 characters',
      passwordNotMatch: 'New passwords do not match',
      contactUs: 'Contact Us',
      logout: 'Logout',
      logoutConfirm: 'Are you sure you want to logout?',
      processing: 'Processing...',
      saving: 'Saving...',
      fullName: 'Full Name',
      phoneNumber: 'Phone / WhatsApp Number',
      fullAddress: 'Full Address',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      notFilled: 'Not filled',
      profileUpdated: 'Profile updated successfully!',
      profileUpdateFailed: 'Failed to update profile',
      nameRequired: 'Full name cannot be empty',
      enterFullName: 'Enter full name',
      phoneExample: 'Example: 08123456789',
      enterFullAddress: 'Enter full address'
    },

    wasteTypes: {
      wood_pellet: 'Wood Pellet',
      wood_chip: 'Wood Chip',
      sawdust: 'Sawdust',
      sampah_rumah: 'Household Waste',
      potongan_kayu: 'Wood Scraps',
      cangkang_sawit: 'Palm Kernel Shell',
      'Wood Pellet': 'Wood Pellet',
      'Wood Chip': 'Wood Chip',
      'Cangkang Sawit': 'Palm Kernel Shell',
      'Serbuk Kayu': 'Sawdust'
    },

    productForm: {
      title: 'Add Biomass Product',
      labelName: 'Product Name',
      labelCategory: 'Category',
      labelPrice: 'Price per Kg (Rp)',
      labelStock: 'Available Stock (Ton)',
      labelLocation: 'Location',
      labelWhatsApp: 'WhatsApp Number (Required)',
      helperWhatsApp: 'Buyers will contact you via this number',
      labelPhoto: 'Upload Product Photo (Required)',
      labelDesc: 'Product Description',
      placeholderName: 'e.g. Wood Pellet Grade A',
      placeholderPrice: 'e.g. 1500',
      placeholderStock: 'e.g. 100',
      placeholderLocation: 'e.g. Jakarta',
      placeholderWhatsApp: '08123456789',
      placeholderDesc: 'Short description of your product (optional)',
      btnCancel: 'Cancel',
      btnSave: 'Save Product',
      btnUploading: 'Uploading...',
      errorName: 'Product name is required',
      errorPrice: 'Price must be greater than 0',
      errorStock: 'Stock must be greater than 0',
      errorWhatsApp: 'WhatsApp number is required',
      errorPhoto: 'Product photo is required',
      successAdd: 'Product added successfully!',
      successUpdate: 'Product updated successfully!',
      errorAdd: 'Failed to add product',
      stockUnit: 'ton',
      available: 'available'
    },

    landing: {
      heroTitle: 'LimbahGuna',
      heroSubtitle: 'Digital Platform for Sustainable Waste and Energy Management',
      featuresTitle: 'Key Features',
      feature1Title: 'Supply Biomass Waste',
      feature1Desc: 'Sell wood pellets, palm shells, etc.',
      feature2Title: 'Biomass Marketplace',
      feature2Desc: 'Buy high-quality biomass fuel.',
      feature3Title: 'Carbon Calculator',
      feature3Desc: 'Calculate your CO2 emission reduction impact.',
      feature4Title: 'Reward Point System',
      feature4Desc: 'Earn points from every supply.',
      stats1Label: 'Kg Biomass Collected',
      stats2Label: 'Kg CO2 Saved',
      btnCta: 'Login / Register Now',
      footerText: '© 2025 LimbahGuna. Indonesia\'s Circular Economy Platform.',
      footerBy: 'By PT Energi Jaya Integra.',
      howItWorksTitle: 'How It Works',
      step1Title: 'Photo Your Waste',
      step1Desc: 'Point your camera at waste or trash around you. Our AI system will automatically recognize its type and quality.',
      step2Title: 'Fast Processing',
      step2Desc: 'Your photo is instantly processed by our control center to provide direct instructions to the sorting system.',
      step3Title: 'Get Rewards',
      step3Desc: 'Waste is sorted into the correct bins, and you automatically earn reward points that can be exchanged for exciting prizes.'
    },

    auth: {
      back: 'Back',
      roleTitle: 'Choose Your Role',
      roleSubtitle: 'Join the LimbahGuna circular economy ecosystem',
      producerTitle: 'Producer Partner',
      producerDesc: 'I process waste & sell biomass products',
      producerFeature1: 'Manage products in Marketplace',
      producerFeature2: 'Validate waste deposits from community',
      producerFeature3: 'Complete producer dashboard',
      publicTitle: 'Eco Partner',
      publicDesc: 'I supply waste & buy energy products',
      publicFeature1: 'Supply biomass waste & earn points',
      publicFeature2: 'Shop energy products in Marketplace',
      publicFeature3: 'Access carbon calculator',
      welcomeTitle: 'Welcome Back',
      welcomeSubtitle: 'Sign in to your LimbahGuna account',
      registerTitle: 'Complete your registration details',
      labelName: 'Full Name',
      labelEmail: 'Email',
      labelPassword: 'Password',
      placeholderName: 'Enter full name',
      placeholderEmail: 'email@example.com',
      placeholderPassword: 'Min 6 characters',
      btnLogin: 'Sign In',
      btnRegister: 'Register Now',
      btnProcessing: 'Processing...',
      haveAccount: 'Already have an account?',
      noAccount: 'Don\'t have an account?',
      linkLogin: 'Sign In',
      linkRegister: 'Register',
      regSuccess: 'Registration successful! Please check your email to confirm your account.'
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('id');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'id' ? 'en' : 'id');
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key;
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
