// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntcgtsnufvhtgaejuuzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Y2d0c251ZnZodGdhZWp1dXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMjA0OTIsImV4cCI6MjA3OTg5NjQ5Mn0.QAvZJtU1njUF4kEqs02zIdGhPGezuhidMzu40bKnXQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});